name: unit-test
on:
  pull_request:
  push:
    branches: "*"
    tags-ignore: "v*"
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          check-latest: true
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: ./test/pytch/run-tests.sh
